name: Sync GitLab Contributions
on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync GitLab to GitHub
        uses: AykutSarac/sync-contrib-calendar-action@v1.0.1
        with:
          gitlab_username: akashkalathiya46
          github_token: ${{ secrets.GITHUB_TOKEN }}
