name: Sync GitLab Contributions
on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync GitLab to GitHub
        uses: furmanp/gitlab-activity-importer@main
        with:
          gitlab_user: akashkalathiya46
          github_user: Akash-ptl
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gitlab_token: ${{ secrets.GITLAB_TOKEN }}
